### ISSUE TITLE
Pedity is now Tree3 Network

### ISSUE THREAD

**Issue by Pedity-Luffy** [stellardevdigest/stellardevdigest.github.io#1]
Pedity is now Tree3 Network. We have launched a new CLI, new website, documentation and reorganizes the project.
All Important project links are at - https://docs.tree3.network/links/
Check us out Tree3 Network (@Tree3Network): https://twitter.com/Tree3Network?s=09

**Comment by robertDurst** [comment]
Please move to the other repo and fill out the application: https://github.com/stellardevdigest/featured_project_dropbox/issues/new/choose

Thanks!
